name: Build & Release Electron App

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6.0.3

      - name: Setup Node.js
        uses: actions/setup-node@v6.4.0
        with:
          node-version: 24.16.0
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build Windows
        run: npm run build:win
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v7.0.1
        with:
          name: windows-build
          path: |
            dist/*.exe
            dist/*.zip

  build-macos:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6.0.3

      - name: Setup Node.js
        uses: actions/setup-node@v6.4.0
        with:
          node-version: 24.16.0
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build macOS
        run: npm run build:mac
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload macOS Artifact
        uses: actions/upload-artifact@v7.0.1
        with:
          name: macos-build
          path: |
            dist/*.dmg
            dist/*.zip

  release:
    needs:
      - build-windows
      - build-macos

    runs-on: ubuntu-latest

    steps:
      - name: Download Windows Artifact
        uses: actions/download-artifact@v8.0.1
        with:
          name: windows-build
          path: release-assets

      - name: Download macOS Artifact
        uses: actions/download-artifact@v8.0.1
        with:
          name: macos-build
          path: release-assets

      - name: Create Release
        uses: softprops/action-gh-release@v3
        with:
          files: release-assets/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
