name: Build & Release Electron App (Windows)

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6.0.3

      - name: Setup Node.js
        uses: actions/setup-node@v6.4.0
        with:
          node-version: 24.16.0
          cache: npm

      - name: Install dependencies
        run: npm ci

      # OPTIONAL tapi sering membantu Electron build stabil
    #   - name: Rebuild native modules
    #     run: npx electron-rebuild

      - name: Build Electron App (Windows)
        run: npm run build
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: List output files (debug)
        run: dir dist

      - name: Upload artifacts (backup)
        uses: actions/upload-artifact@v7.0.1
        with:
          name: windows-build
          path: dist/**

      - name: Create GitHub Release & Upload Installer
        uses: softprops/action-gh-release@v3
        with:
          files: |
            dist/*.exe
            dist/*.nsis.exe
            dist/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
